# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            nonprofit capacity building
tagline:          'Growing organizations that make the world a better place'
description:      'a Book<br>a Workshop<br>a Community<br>a Knowledge Repository'
url:              https://nonprofit.mba
baseurl:          /

author:           
  name:           'Juan Pablo Berrizbeitia'
  url:            'http://jpberriz.com'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jpberriz/npmba

include:          ['_pages']

# Site search 
tipue_search:
  include:
    pages:        true

# Google Analytics
google_analytics: UA-144919967-1